//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QandaQuizEntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QandaQuizContext : DbContext
    {
        public QandaQuizContext()
            : base("name=QandaQuizContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<QuizAnswer> quizAnswers { get; set; }
        public virtual DbSet<QuizDetail> quizDetails { get; set; }
        public virtual DbSet<QuizPlayDetail> quizPlayDetails { get; set; }
        public virtual DbSet<QuizQuestion> quizQuestions { get; set; }
        public virtual DbSet<TopupAccount> topupAccounts { get; set; }
        public virtual DbSet<userCountry> userCountries { get; set; }
        public virtual DbSet<LogEntry> LogEntries { get; set; }
    }
}
