//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QandaQuizEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuizDetail()
        {
            this.QuizPlayDetails = new HashSet<QuizPlayDetail>();
        }
    
        public int Id { get; set; }
        public string quizTitle { get; set; }
        public string quizDescription { get; set; }
        public decimal quizPrizeMoney { get; set; }
        public int quizTimesNumberOfEntriesAllowed { get; set; }
        public int quizWinnerNumber { get; set; }
        public string quizWinnerId { get; set; }
        public System.DateTime quizAvtiveDateTime { get; set; }
        public bool quizLapsed { get; set; }
        public bool quizCurrentlyActive { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuizPlayDetail> QuizPlayDetails { get; set; }
        public virtual QuizQuestion QuizQuestion { get; set; }
    }
}
