//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QandaQuizEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuizQuestion()
        {
            this.QuizAnswers = new HashSet<QuizAnswer>();
        }
    
        public int Id { get; set; }
        public string quizQuestionText { get; set; }
        public bool quizQuestionHasImage { get; set; }
        public string quizQuestionImagePath { get; set; }
        public bool quizQuestionHasVideo { get; set; }
        public string quizQuestionVideoPath { get; set; }
        public int quizQuestionNumberOfAnswers { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuizAnswer> QuizAnswers { get; set; }
        public virtual QuizDetail QuizDetail { get; set; }
    }
}
