//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QandaQuizEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizPlayDetail
    {
        public int Id { get; set; }
        public System.DateTime quizSubmittedDateTime { get; set; }
        public decimal quizPlayAmount { get; set; }
        public Nullable<int> quiz_Id { get; set; }
        public Nullable<int> quizAnswer_Id { get; set; }
        public string user_Id { get; set; }
        public bool IsThisFreePlay { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual QuizAnswer QuizAnswer { get; set; }
        public virtual QuizDetail QuizDetail { get; set; }
    }
}
