//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QandaQuizEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopupAccount
    {
        public string Id { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime topupDateTime { get; set; }
        public string paypalToken { get; set; }
        public string payerID { get; set; }
        public Nullable<System.DateTime> paymentSuccessfulDateTime { get; set; }
        public string user_Id { get; set; }
        public Nullable<decimal> finalPaymentAmount { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
