// <auto-generated />
namespace QandaQuizNet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class dbChangesv5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbChangesv5));
        
        string IMigrationMetadata.Id
        {
            get { return "201509192344377_dbChangesv5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
